# Generated by Django 2.2.17 on 2021-01-28 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_auto_20210128_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_connected',
        ),
        migrations.AddField(
            model_name='tweet',
            name='comments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tweet.Comment'),
            preserve_default=False,
        ),
    ]
