# Generated by Django 2.2.17 on 2021-01-28 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0006_auto_20210128_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tweet.Comment'),
        ),
    ]
